name: Complete workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      -  main
      -  master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        mongodb-version: [4.2]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Run eslint
        run: npx eslint 'src/**'

      - name: Run all tests
        run: npm run test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}

      - name: Deploy application
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "enquetesapi"
          heroku_email: "allan_net@live.com"
          buildpack: "https://github.com/zidizei/heroku-buildpack-tsc#v2.0"